name: Frontend and Backend Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-checks:
    name: Frontend Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            echo "::warning::Missing pnpm-lock.yaml. Generating new lockfile..."
            pnpm install --no-frozen-lockfile
          fi
      
      - name: Run Prettier
        run: pnpm exec prettier --check "./src/**/*.{js,ts,jsx,tsx}"

      - name: Run ESLint
        run: pnpm exec eslint ./src --ext .js,.ts,.jsx,.tsx

      - name: Run tsc
        run: pnpm tsc --noEmit

  backend-checks:
    name: Backend Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy  
          override: true

      - name: cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check --manifest-path ./src-tauri/Cargo.toml

      - name: cargo clippy
        uses: actions/checkout@v4
        with:
          command: clippy
          args: --target aarch64-linux-android --manifest-path ./src-tauri/Cargo.toml
      
      - name: cargo test
        uses: actions/checkout@v4
        with:
          command: test
          args: --all-features  --manifest-path ./src-tauri/Cargo.toml